---
title: "Spatial tests"
author: "R. Michisaki"
date: "December 7, 2017"
output: ioslides_presentation
---
<!--
https://cran.r-project.org/doc/contrib/intro-spatial-rl.pdf 
x <- c("ggmap", "rgdal", "rgeos", "maptools", "dplyr", "tidyr", "tmap")
# install.packages(x) # warning: uncommenting this may take a number of minutes
lapply(x, library, character.only = TRUE) # load the required packages

-->
Add some text here

```{r setup, include=FALSE}
df <- read.csv("https://raw.githubusercontent.com/reiko-pm/ds_collaborate/gh-pages/data/Line67_stations.csv")
loc <- paste0(df$station,": ",df$dec_long,", ",df$dec_lat)

library(leaflet) #install.packages("leaflet")


```

## Leaflet Line 67 map
Hover over blue markers for station name and location


```{r Line67, echo = FALSE}
leaflet(df) %>% 
  addProviderTiles(providers$Esri.NatGeoWorldMap) %>%
  addCircleMarkers(~dec_long, ~dec_lat,
                   radius = 6,
                   label = loc,
                   labelOptions = labelOptions(noHide = F)) %>% 
  setView(-123.48,36.120,zoom = 8)

```

## SUMMARY

```{r summary}
summary(df)
```

